env: local
run_name: base_hierarchical
paths:
  features: "..\\outputs\\features"
  hierarchical_name: hierarchical_filtered
  tokenized_dir: tokenized
tree:
  cutoff_level: 5
  extend_level: 5
  filter_database: true