env: local
paths:
  data_path: "../outputs/synthea10k" 
  model_path: "outputs/pretraining/synthea10k"
  outcomes_path: "../outputs/synthea10k/outcomes/TEST.pt"
  checkpoint_epoch: 2
  run_name: "test_uncensored_large"

encode_pos_only: false
train_data:
  num_patients: null
  n_procs: null
val_data:
  num_patients: null
  n_procs: null

outcomes: 
  outcome1:
     type: null
     n_hours: null # censor time
     censor_type: null
  # outcome2:
  #   type: TEST_OUTCOME
  #   n_hours: 1 # censor time
  #   censor_type: TEST_OUTCOME


forwarder_args:
  batch_size: 512
  pooler:
    _target_: evaluation.poolings.MeanPooling
  
    
 
