env: local

paths:
  model_path: "../outputs/pretraining/test/finetune_TEST_OUTCOME_censored_5_days_post_TEST_OUTCOME_test"
  run_name: "evaluate"

metrics:
  accuracy:
    _target_: evaluation.metrics.Accuracy
    threshold: 0.6
  balanced_accuracy:
    _target_: evaluation.metrics.Balanced_Accuracy
  precision:
    _target_: evaluation.metrics.Precision
  recall:
    _target_: evaluation.metrics.Recall
  roc_auc:
    _target_: evaluation.metrics.ROC_AUC
  pr_auc:
    _target_: evaluation.metrics.PR_AUC

data:
  min_len: 1
  test_data_dir: "../outputs/pretraining/test/finetune_TEST_OUTCOME_censored_5_days_post_TEST_OUTCOME_test" 
