env: local
paths:
  pretrain_model_path: "../outputs/pretraining/test"
  outcome: "../outputs/features/outcomes/TEST_OUTCOME/TEST_OUTCOME.pt"
  run_name: "test_stats"
  # tokenized_dir: "tokenized"
  tokenized_file: "tokenized_finetune.pt" # can also be a list
  tokenized_pids: "pids_finetune.pt" # can also be a list
  # predefined_splits: outputs/pretraining/behrt_test/finetune_TEST_OUTCOME_censored_5_days_post_TEST_OUTCOME_test_2
  # exclude_pids: outputs\pretraining\behrt_test\finetune_TEST_OUTCOME_censored_4_days_post_TEST_OUTCOME_test\test_pids.pt
data:
  num_patients: 300 #300
  val_split: 0.1
  test_split: 0.1
  truncation_len: 30
  select_censored: false
  # gender: M
  min_age: 0
  max_age: 70
  # min_len: null
  min_len: 2
  censorer:
   _target_: data_fixes.censor.EQ_Censorer
  number_of_train_patients: 10

model:
  behrt_embeddings: false

outcome: 
  type: TEST_OUTCOME
  n_hours: 124 # censor time
  censor_type: TEST_OUTCOME