defaults:
  - metrics: null
  - model: hierarchical
  - optimizer: defaults
  - paths: defaults
  - trainer_args: defaults

  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

paths:
  encoded_suffix: pretrain

ignore_special_tokens: true
info: true

paths:
  vocabulary: 'h_vocabulary.pt'

metrics: null